### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by stuporglue** [rhiever/reddit-analysis#51]
I tried running this against /r/gis and got an error: 

Traceback (most recent call last):
  File "/usr/local/bin/word_freqs", line 9, in <module>
    load_entry_point('redditanalysis==1.0.1', 'console_scripts', 'word_freqs')()
  File "/Library/Python/2.7/site-packages/redditanalysis/__init__.py", line 415, in main
    out_text = str("{0}:{1}\n".format(word, ALL_WORDS[word]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 0: ordinal not in range(128)

I installed it with pip on OSX 10.10.4

**Comment by rhiever** [comment]
You'll need to run this script on Python 3 for it to handle unicode characters like that properly. Python 2 is wonky with how it parses unicode characters.

I'll file this as a bug in the script for now. Not sure when I'll get to it though -- Python 2 is quite outdated.

**Comment by stuporglue** [comment]
That makes sense, thanks for the quick response.
